services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC API
    volumes:
      - ~/.qdrant/storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ollama_network

  ragdocs:
    build: .
    image: ragdocs
    container_name: ragdocs

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama/models:/root/.ollama/models:rw
    networks:
      - ollama_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

networks:
  ollama_network:
    driver: bridge
