services:

  ragdocs:
    build: .
    image: ragdocs
    container_name: ragdocs
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC API
    volumes:
      - ${QDRANT_STORAGE:-~/.qdrant/storage}:/qdrant/storage:rw
    environment:
      - QDRANT_ALLOW_RECOVERY=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ragdocs_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME:-~/.ollama}:/root/.ollama:rw
    networks:
      - ragdocs_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

networks:
  ragdocs_network:
    driver: bridge
